### ISSUE TITLE
Suggest support nuxtlabs ui

### ISSUE THREAD

**Issue by IronnMan** [hylarucoder/ChatGPT-Nuxt#39]
- github: https://github.com/nuxtlabs/ui
- website: https://ui.nuxtlabs.com/getting-started

**Comment by hylarucoder** [comment]
@IronnMan 谢谢提醒, v0.1 版本之后会详细分析一下包占用情况. 如果大小合适会引入的.

**Comment by hylarucoder** [comment]
@IronnMan 看了一下,很强大. 已经加上. https://github.com/hylarucoder/ChatGPT-Nuxt/pull/42/files
